version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: gin_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: gin_api
    image: bifidokk/gin-api:latest
    ports:
      - ${API_PORT}:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  migrations:
    container_name: gin_migrations
    image: bifidokk/gin-migrations:latest
    command: migrate apply --url ${POSTGRES_MIGRATION_DSN} --dir "file://migrations"
    depends_on:
      postgres:
        condition: service_healthy
  