version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: gin_db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: gin_api
    build:
      context: ../
      dockerfile: ./.docker/api/Dockerfile.dev
    ports:
      - 8081:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  migrations:
    container_name: gin_migrations
    build:
      context: ../
      dockerfile: ./.docker/migrations/Dockerfile.dev
    command: migrate apply --url ${POSTGRES_MIGRATION_DSN} --dir "file://migrations"
    depends_on:
      postgres:
        condition: service_healthy