name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/api/Dockerfile
          push: true
          tags: bifidokk/gin-api:latest
          build-args: |
            DB_DSN=${{ secrets.DB_DSN }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_TTL=${{ secrets.JWT_TTL }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            DOTENV=${{ secrets.DOTENV }}

      -
        name: Build and push migration image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/migrations/Dockerfile
          push: true
          tags: bifidokk/gin-migrations:latest
      - 
        name: Restart Docker compose with fresh images
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /var/www/gin-api
            git pull
            docker image prune --all --force
            docker compose --file ./.docker/docker-compose.yml pull
            docker compose --file ./.docker/docker-compose.yml down
            docker compose --file ./.docker/docker-compose.yml --env-file ./.docker/.env.prod up -d
